language: minimal
dist: trusty
os: linux
env:
- HDF5_VERSION=1.8.14
- HDF5_VERSION=1.8.21
- HDF5_VERSION=1.10.1
- HDF5_VERSION=1.10.5
install:
- source helper.sh
- export HDF5_DIR=$HOME/.hdf5build
- install_hdf5
- git_config
- upload_tar
